# Generated by Django 4.2.7 on 2023-12-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_pm', '0003_alter_purchaseorder_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='acknowledgment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
