# Generated by Django 4.2.7 on 2023-12-01 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms_pm', '0004_alter_purchaseorder_acknowledgment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='acknowledgment_date',
            new_name='acknowledgement_date',
        ),
    ]
