# Generated by Django 4.2.7 on 2023-12-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_pm', '0005_rename_acknowledgment_date_purchaseorder_acknowledgement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='acknowledgement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
