# Generated by Django 4.2.7 on 2023-12-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_pm', '0010_alter_vendor_address_alter_vendor_contact_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperformance',
            name='average_response_time',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='historicalperformance',
            name='fulfillment_rate',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='historicalperformance',
            name='on_time_delivery_rate',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='historicalperformance',
            name='quality_rating_avg',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
